Behat test

diff --git a/.github/workflows/moodle-plugin-ci.yml b/.github/workflows/moodle-plugin-ci.yml
--- a/.github/workflows/moodle-plugin-ci.yml
+++ b/.github/workflows/moodle-plugin-ci.yml
@@ -30,7 +30,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        php: ['8.0', '8.1', '8.2']
+        php: ['8.2']
         moodle-branch: ['MOODLE_403_STABLE']
         database: [pgsql, mariadb]
 
@@ -62,55 +62,55 @@ jobs:
           DB: ${{ matrix.database }}
           MOODLE_BRANCH: ${{ matrix.moodle-branch }}
 
-      - name: PHP Lint
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phplint
+      # - name: PHP Lint
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci phplint
 
-      - name: PHP Mess Detector
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpmd
+      # - name: PHP Mess Detector
+      #   continue-on-error: true # This step will show errors but will not fail
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci phpmd
 
-      - name: Moodle Code Checker
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpcs --max-warnings 0
+      # - name: Moodle Code Checker
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci phpcs --max-warnings 0
 
-      - name: Boost Union Code Checker
-        uses: JJ/github-pr-contains-action@releases/v14
-        if: ${{ !cancelled() }}
-        with:
-          github-token: ${{github.token}}
-          diffDoesNotContain: "theme->settings->"
+      # - name: Boost Union Code Checker
+      #   uses: JJ/github-pr-contains-action@releases/v14
+      #   if: ${{ !cancelled() }}
+      #   with:
+      #     github-token: ${{github.token}}
+      #     diffDoesNotContain: "theme->settings->"
 
-      - name: Moodle PHPDoc Checker
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpdoc --max-warnings 0
+      # - name: Moodle PHPDoc Checker
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci phpdoc --max-warnings 0
 
-      - name: Validating
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci validate
+      # - name: Validating
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci validate
 
-      - name: Check upgrade savepoints
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci savepoints
+      # - name: Check upgrade savepoints
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci savepoints
 
-      - name: Mustache Lint
-        continue-on-error: true # This step will show errors but will not fail
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci mustache
+      # - name: Mustache Lint
+      #   continue-on-error: true # This step will show errors but will not fail
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci mustache
 
       - name: Grunt
         if: ${{ !cancelled() }}
         run: moodle-plugin-ci grunt --max-lint-warnings 0
 
-      - name: PHPUnit tests
-        if: ${{ !cancelled() }}
-        run: moodle-plugin-ci phpunit --fail-on-warning
+      # - name: PHPUnit tests
+      #   if: ${{ !cancelled() }}
+      #   run: moodle-plugin-ci phpunit --fail-on-warning
 
       - name: Behat features
         if: ${{ !cancelled() }}
         run: moodle-plugin-ci behat --profile chrome --suite boost_union
 
-      - name: Mark cancelled jobs as failed.
-        if: ${{ cancelled() }}
-        run: exit 1
+      # - name: Mark cancelled jobs as failed.
+      #   if: ${{ cancelled() }}
+      #   run: exit 1
