Fixed Grunt CI

diff --git a/.github/workflows/moodle-plugin-ci.yml b/.github/workflows/moodle-plugin-ci.yml
--- a/.github/workflows/moodle-plugin-ci.yml
+++ b/.github/workflows/moodle-plugin-ci.yml
@@ -62,39 +62,39 @@ jobs:
           DB: ${{ matrix.database }}
           MOODLE_BRANCH: ${{ matrix.moodle-branch }}
 
-      # - name: PHP Lint
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci phplint
+      - name: PHP Lint
+        if: ${{ always() }}
+        run: moodle-plugin-ci phplint
 
-      # - name: PHP Copy/Paste Detector
-      #   continue-on-error: true # This step will show errors but will not fail
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci phpcpd
+      - name: PHP Copy/Paste Detector
+        continue-on-error: true # This step will show errors but will not fail
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpcpd
 
-      # - name: PHP Mess Detector
-      #   continue-on-error: true # This step will show errors but will not fail
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci phpmd
+      - name: PHP Mess Detector
+        continue-on-error: true # This step will show errors but will not fail
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpmd
 
-      # - name: Moodle Code Checker
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci codechecker --max-warnings 0
+      - name: Moodle Code Checker
+        if: ${{ always() }}
+        run: moodle-plugin-ci codechecker --max-warnings 0
 
-      # - name: Moodle PHPDoc Checker
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci phpdoc
+      - name: Moodle PHPDoc Checker
+        if: ${{ always() }}
+        run: moodle-plugin-ci phpdoc
 
-      # - name: Validating
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci validate
+      - name: Validating
+        if: ${{ always() }}
+        run: moodle-plugin-ci validate
 
-      # - name: Check upgrade savepoints
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci savepoints
+      - name: Check upgrade savepoints
+        if: ${{ always() }}
+        run: moodle-plugin-ci savepoints
 
-      # - name: Mustache Lint
-      #   if: ${{ always() }}
-      #   run: moodle-plugin-ci mustache || true
+      - name: Mustache Lint
+        if: ${{ always() }}
+        run: moodle-plugin-ci mustache || true
 
       - name: Grunt
         if: ${{ always() }}
@@ -106,4 +106,4 @@ jobs:
 
       - name: Behat features
         if: ${{ always() }}
-        run: moodle-plugin-ci behat --profile chrome --auto-rerun 0 --suite boost_union --tags @theme_boost_union_smartmenu
+        run: moodle-plugin-ci behat --profile chrome --auto-rerun 0 --suite boost_union
